# Generated by Django 4.1.7 on 2023-03-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsetaq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='categories',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
