# Generated by Django 4.1.7 on 2023-03-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsetaq', '0003_alter_expenses_categories_alter_income_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.IntegerField(),
        ),
    ]
